source 'https://rubygems.org'

gem 'jekyll', '~> 3.10'
gem 'liquid', '~> 4.0.4'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-gist'
gem 'jekyll-paginate'
gem 'jemoji'
gem 'webrick', '~> 1.8'
gem 'csv'
gem 'logger'
gem 'base64'
gem 'bigdecimal'

gem 'kramdown-parser-gfm'
